// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Proof is an autogenerated mock type for the Proof type
type Proof struct {
	mock.Mock
}

// Encode provides a mock function with given fields:
func (_m *Proof) Encode() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

type mockConstructorTestingTNewProof interface {
	mock.TestingT
	Cleanup(func())
}

// NewProof creates a new instance of Proof. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProof(t mockConstructorTestingTNewProof) *Proof {
	mock := &Proof{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
