// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TextMarshaler is an autogenerated mock type for the TextMarshaler type
type TextMarshaler struct {
	mock.Mock
}

// MarshalText provides a mock function with given fields:
func (_m *TextMarshaler) MarshalText() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UnmarshalText provides a mock function with given fields: text
func (_m *TextMarshaler) UnmarshalText(text []byte) error {
	ret := _m.Called(text)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTextMarshaler interface {
	mock.TestingT
	Cleanup(func())
}

// NewTextMarshaler creates a new instance of TextMarshaler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTextMarshaler(t mockConstructorTestingTNewTextMarshaler) *TextMarshaler {
	mock := &TextMarshaler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
