name: e2e

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind

    steps:
      - name: Check machine OS
        run: |
          echo "Machine OS: ${{ runner.os }}"
      - name: Check Docker version
        run: |
          docker version
      - name: Install Docker Compose
        uses: ndeloof/install-docker-compose@v0.0.1
        with:
          version: v2.5.1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in current dir
        run: |
          pwd
          ls -la

      - name: Create proj folder and add keys and genesis.json
        run: |
          ls -la clients/geth/specular/data
          mkdir project && cd project
          mkdir specular-datadir && cd specular-datadir
          cp ../../clients/geth/specular/data/keys/sequencer.prv ./key.prv
          cp ../../clients/geth/specular/data/password.txt .
          cp ../../clients/geth/specular/data/base_genesis.json ./genesis.json

      - name: Start up containers
        run: |
          pwd 
          ls -la
          docker-compose -f docker/docker-compose-integration-test.yml up -d --build

      - name: Wait for containers
        run: |
          pwd
          ls -la
          while ! docker-compose -f docker/docker-compose-integration-test.yml ps -q | xargs docker inspect -f '{{ .State.Health.Status }}' | grep -q healthy; do
              sleep 1
          done

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Run test
        run: |
          pwd
          ls -la
          cd contracts/scripts
          node testing.ts

      - name: Stop and remove containers
        run: |
          pwd 
          ls -la
          docker-compose -f docker/docker-compose-integration-test.yml down
