name: e2e

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run end-to-end tests
        run: |
          cd contracts
          yarn install
          yarn run ts-node scripts/docker_start.ts

# jobs:
#   e2e:
#     runs-on: ubuntu-latest

#     services:
#       docker:
#         image: docker:dind

#     steps:
#       - name: Check machine OS
#         run: |
#           echo "Machine OS: ${{ runner.os }}"
#       - name: Check Docker version
#         run: |
#           docker version
#       - name: Install Docker Compose
#         uses: ndeloof/install-compose-action@v0.0.1
#         with:
#           version: v2.5.1

#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Update Git submodules
#         run: |
#           git submodule init
#           git submodule update --recursive

#       - name: List files in current dir
#         run: |
#           pwd
#           ls -la

#       - name: Create proj folder and add keys and genesis.json
#         run: |
#           ls -la clients/geth/specular/data
#           mkdir project && cd project
#           mkdir specular-datadir && cd specular-datadir
#           cp ../../clients/geth/specular/data/keys/sequencer.prv ./key.prv
#           cp ../../clients/geth/specular/data/password.txt .
#           cp ../../clients/geth/specular/data/base_genesis.json ./genesis.json

#       - name: Install node
#         uses: actions/setup-node@v2
#         with:
#           node-version: "18.x"

#       # - name: Install dependencies
#       #   run: |
#       #     npm install ts-node

#       # - name: Install Docker Compose
#       #   run: |
#       #     sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
#       #     sudo chmod +x /usr/local/bin/docker-compose

#       # - name: Check Docker Compose version
#       #   run: |
#       #     docker-compose --version

#       - name: Start up containers
#         run: |
#           pwd
#           ls -la
#           cd project
#           rm -rf project/specular-datadir/geth/
#           npx ts-node ../contracts/scripts/docker_start.ts
#           wget https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh
#           chmod +x wait-for-it.sh
#           sleep 30
#           docker ps
#           docker logs hardhat
#           docker logs sequencer
#           ./wait-for-it.sh -t 240 127.0.0.1:8545
#           ./wait-for-it.sh -t 240 127.0.0.1:4011
#           docker logs hardhat
#           docker logs sequencer

#       - name: Run testing script
#         run: |
#           pwd
#           ls -la
#           cd contracts
#           yarn install
#           npx hardhat deploy --network localhost
#           cd scripts
#           yarn run ts-node /home/runner/work/specular/specular/contracts/scripts/testing.ts
#           docker logs hardhat
#           docker logs sequencer

#       - name: Stop and remove containers
#         run: |
#           pwd
#           ls -la
#           npx ts-node contracts/scripts/docker_start.ts
