name: e2e

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Git submodules
        run: |
          git submodule init
          git submodule update --recursive

      - name: Run end-to-end tests
        run: |
          cd contracts
          yarn install
          yarn run ts-node scripts/run_e2e.ts
