name: e2e

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Git submodules
        run: |
          git submodule init
          git submodule update --recursive

      - name: Create proj folder and add keys and genesis.json
        run: |
          cd contracts
          ls -la ../clients/geth/specular/data
          mkdir project && cd project
          mkdir specular-datadir && cd specular-datadir
          cp ../../../clients/geth/specular/data/keys/sequencer.prv ./key.prv
          cp ../../../clients/geth/specular/data/password.txt .
          cp ../../../clients/geth/specular/data/base_genesis.json ./genesis.json

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: |
          npm install ts-node

      - name: Run end-to-end tests
        run: |
          pwd
          ls -la
          cd contracts/project
          rm -rf project/specular-datadir/geth/
          cd ..
          yarn install
          yarn run ts-node scripts/run_e2e.ts
