name: e2e

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind

    steps:
      - name: Create proj folder and add keys and genesis.json
        run: |
          ls -la clients/geth/specular/data
          mkdir project && cd project
          mkdir specular-datadir && cd specular-datadir
          cp ../../clients/geth/specular/data/keys/sequencer.prv ./key.prv
          cp ../../clients/geth/specular/data/password.txt .
          cp ../../clients/geth/specular/data/base_genesis.json ./genesis.json

      - name: Start up containers
        run: |
          pwd
          ls -la
          cd project
          rm -rf project/specular-datadir/geth/
          cd ../contracts
          yarn install
          yarn run ts-node scripts/docker_start.ts
