name: e2e

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update Git submodules
        run: |
          git submodule init
          git submodule update --recursive

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: |
          npm install ts-node

      - name: Run end-to-end tests
        run: |
          pwd
          ls -la
          cd contracts
          yarn install
          yarn run ts-node scripts/run_e2e.ts
