name: Forge Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: same_content_newer
  test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          timeout-minutes: 10
          version: nightly

      - name: Run forge install
        run: forge install

      - name: Install yarn dependencies
        run: yarn install

      - name: Run tests
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
        run: forge test -vvv
